# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_grupoinvestigacion_mencionhonor_modalidad_nivelestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='grupoInvestigacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.GrupoInvestigacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='mencionHonor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.MencionHonor'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Modalidad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nivelEstudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.NivelEstudio'),
        ),
    ]
