# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20160205_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Director',
        ),
        migrations.RenameModel(
            old_name='NivelEstudio',
            new_name='TituloAplicado',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='profesor',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nivelEstudio',
            new_name='tituloAplicado',
        ),
    ]
