# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_auto_20160212_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='grupoinvestigacion',
            options={'verbose_name_plural': 'Grupos de investigaci\xf3n'},
        ),
        migrations.AlterModelOptions(
            name='mencionhonor',
            options={'verbose_name_plural': 'Mencion de honor'},
        ),
        migrations.AlterModelOptions(
            name='modalidad',
            options={'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={'verbose_name_plural': 'Periodos acad\xe9micos'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tituloaplicado',
            options={'verbose_name_plural': 'T\xedtulo aplicado'},
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='anio',
            field=models.CharField(max_length=255, verbose_name='A\xf1o'),
        ),
    ]
