# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20160212_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together=set([('codigo',)]),
        ),
    ]
