# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_auto_20160212_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='paginaWeb',
            field=models.CharField(default='pegasus.javeriana.edu.co/~', editable=False, max_length=255, null=True),
        ),
    ]
