# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_auto_20160212_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='paginaWeb',
            field=models.CharField(default='pegasus.javeriana.edu.co/~', max_length=255, null=True),
        ),
    ]
