# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_periodoacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='paginaWeb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='autor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
