# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_auto_20160212_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='paginaWeb',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
