# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20160206_0408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together=set([('anio', 'semestre')]),
        ),
    ]
